version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-00c8d1110876159bb
              - subnet-075d6a254031a4b46
            SecurityGroups:
              - sg-0073524d1f249df00
            AssignPublicIp: ENABLED
Hooks:
  - BeforeAllowTraffic: "arn:aws:lambda:ap-northeast-1:533876055951:function:ashimizu-wordpress-before-allow-traffic"
  - AfterAllowTraffic: "arn:aws:lambda:ap-northeast-1:533876055951:function:ashimizu-wordpress-after-allow-traffic"
